### ISSUE TITLE
Detect more browsers

### ISSUE THREAD

**Issue by Sytten** [mattsse/chromiumoxide#111]
Headless chrome added support to detect more browsers (https://github.com/atroche/rust-headless-chrome/blob/aaa6cb03efefbe67996f35802860c6d7fce3b14b/src/browser/mod.rs#L430-L442), do you want me to port those?
I don't think this would be an issue, but we probably want to rework the order in which they are tried.
The biggest gain is most likely from the support of edge.

**Comment by mattsse** [comment]
definitely, 

the corresponding code is here

https://github.com/mattsse/chromiumoxide/blob/449b35414846f04417d3888f5af4f0d55d7dba43/src/browser.rs#L647-L653

do you want to take this on and reshuffle the order as you see fit?

**Comment by Sytten** [comment]
Yeah I will push a PR for it and we can discuss it there!

**Comment by Sytten** [comment]
@mattsse PR is ready for a first review pass!
