### ISSUE TITLE
Set language to english

### ISSUE THREAD

**Issue by Sytten** [mattsse/chromiumoxide#113]
I am not a chrome expert but concerning the `README` notice for english (`A: Check that your chromium language settings are set to English`) I am wondering if it would help to pass `--lang=en_US` to the process?

**Comment by mattsse** [comment]
> I am wondering if it would help to pass --lang=en_US to the process?

oh, didn't know about that option.
yes definitly.

**Comment by Sytten** [comment]
Perfect I can push a PR for that

**Comment by escritorio-gustavo** [comment]
Was this change applied? The README still mentions the language problem

**Comment by Sytten** [comment]
No I forgot to do it, its a one line change though if you want to push a pr

**Comment by escritorio-gustavo** [comment]
Done. I don't really have much experience with PR's, so I hope I did it correctly
