### ISSUE TITLE
release new version plz

### ISSUE THREAD

**Issue by DCjanus** [mattsse/chromiumoxide#141]
Hi, I'm using this great crate to build something, and without [this commit](https://github.com/mattsse/chromiumoxide/commit/8fc6fed773f2c62842b240e238e1cf8a3bf08540), there would be too many CLOSE_WAIT connection leak in my situation.

Would you mind to release a new version?

**Comment by mattsse** [comment]
hey, thanks for the ping

sorry for the delay.

just released 0.5.0
