### ISSUE TITLE
How to update .pdl files

### ISSUE THREAD

**Issue by AlexStorm1313** [mattsse/chromiumoxide#164]
I'm wondering how I can elegantly update the .pdl files used for rust code generation. What I have seen looking through the code is that there is a revision variable that can be set, but does this automatically mean the .pdl files for that revision are downloaded from e.x. https://github.com/ChromeDevTools/devtools-protocol or is this variable set manually to match the included .pdl files in the project? My use case in this instance is that I want to use the unstable 1.3 protocol. 

I may be getting ahead of myself but, would it be nice to set the protocol version with a feature flag just like the runtime is specified?

Edit: It seems like running the test(generate.rs) with a new revision specified updates the pdl files and subsequently updates the generated rust code. Can someone give some more explanation on this topic. It seems like the docs on this topic are outdated.

**Comment by Sytten** [comment]
The pdl is updated by a test, no ideal but it works.
I will pull the pdl of the revision number and build it. You can track the mapping of revision to chrome version here: https://googlechromelabs.github.io/chrome-for-testing/

**Comment by Sytten** [comment]
Closed by #245 @mattsse
