### ISSUE TITLE
Use new headless mode.

### ISSUE THREAD

**Issue by makindotcc** [mattsse/chromiumoxide#183]
Currently library passes ``--headless`` switch instead of ``--headless=new``
https://github.com/mattsse/chromiumoxide/blob/88470cabec15ffc2a91dc5579ec142e921d59eab/src/browser.rs#L823
Old headless, according to the chrome's blog, is separate browser implementation which leads to being detected by antibots like cloudflare waf.
https://developer.chrome.com/articles/new-headless/

I think we could just explicitly use ``--headless=new``.

**Comment by Sytten** [comment]
We will need to update the chromium version used first and we will want to give the choice to the user.
