### ISSUE TITLE
0.5.8 release?

### ISSUE THREAD

**Issue by j-mendez** [mattsse/chromiumoxide#220]
Hi, thank you for the crate. Was wondering when 0.5.8 is planned? Looking forward to the `0.12` reqwest bump. Just wondering if I need to do a fork to do a temp release etc.

**Comment by mattsse** [comment]
anything else that should be bumped before triggering a new release?

**Comment by j-mendez** [comment]
> anything else that should be bumped before triggering a new release?

taking a quick look.

**Comment by j-mendez** [comment]
> anything else that should be bumped before triggering a new release?

`bytes: 1.6.0`

Should be it. Thanks!

**Comment by mattsse** [comment]
could you perhaps open a pr for these? will get to it by EOD

**Comment by j-mendez** [comment]
> could you perhaps open a pr for these? will get to it by EOD

on it.
