### ISSUE TITLE
browser.new_page(&url) stays blocked

### ISSUE THREAD

**Issue by buave** [mattsse/chromiumoxide#240]
Hi, thank you for this great project. I'm opening an issue because I don't understand, I don't know if it's a bug or if it's me who's taking it wrong.

To sum up, I need to take screenshots of a website with an X URL. My program works, and for my tests, I put all sorts of URLs.
But with “ https://piped.bauve.link " arriving at ``browser.new_page(“https://piped.bauve.link”)`` the program freezes (the URL is valid and functional) I am forced to stop the program.
I have no errors, nothing at all. It just hangs

The weirdest thing is that out of 20 tries, the URL goes through at least once and continues on its way to take a screenshot, and then it works. But if I restart it, it doesn't work anymore. 

I tested with ``.with_head()`` chromium opens and enters the URL, the page loads, but the program remains blocked.

To prevent it from blocking the program indefinitely, I've added a timeout, but I'd like to understand why it doesn't work with this particular link.

I can't provide all the code, but here's the part where there's a problem:
```rust
pub async fn screenshot(
    id: String,
    url: String,
    md5_old: String,
) -> Result<(String, bool), Box<dyn std::error::Error>> {
    let (mut browser, mut handler) = Browser::launch(
        BrowserConfig::builder()
            .viewport(Viewport {
                width: 1920,
                height: 1080,
                device_scale_factor: Some(1.0),
                has_touch: false,
                is_landscape: false,
                emulating_mobile: false,
            })
            .build()?,
    )
    .await?;

    let handle = task::spawn(async move {
        while let Some(h) = handler.next().await {
            if h.is_err() {
                break;
            }
        }
    });

    println!("Connecting to {}", url.clone());


    // The program blocks here
    // the variable url = "https://piped.bauve.link"
    let page_result = timeout(Duration::from_secs(10), browser.new_page(&url)).await;



    let page = match page_result {
        Ok(Ok(page)) => page,
        Ok(Err(e)) => {
            println!("Error creating page: {}", e);
            browser.close().await?;
            std::process::exit(1);
        }
        Err(e) => {
            println!("Timeout error: {}", e);
            browser.close().await?;
            std::process::exit(1);
        }
    };    

    sleep(Duration::from_secs(10)).await;

    let screenshot = page
        .screenshot(ScreenshotParams::builder().full_page(false).build())
        .await?;

...
```

Thanks in advance

**Comment by goni098** [comment]
I also got  error with new_page() method. This is its error 
`Cdp error: ChannelSendError( Send( SendError { kind: Disconnected, }, ), )`
It was working fine before

**Comment by maxwell8888** [comment]
I'm also getting `Error: ChannelSendError(Canceled(Canceled))` when trying to run the wikipedia example.

**Comment by buave** [comment]
Hello, I'm back for an update.

I tried the code by switching to an older version (0.6.0) I was on 0.7.0. But it didn't change anything.
I've noticed that my page loads when I load it for the first time, but then I get the problem mentioned above. The problem came from cookies in the cache. I put the browser in incognito mode, so as never to save cookies, and that solved the problem. So in the end, the problem had more to do with the site than with the code.

I've noticed that my page loads when I load it for the first time, but then I get the problem mentioned above. The problem came from cookies in the cache. I put the browser in incognito mode, so as never to save cookies, and that solved the problem. 

So in the end, the problem had more to do with the site than with the code.

PS: @maxwell8888 @goni098 I'm going to close this issue, please open your issue, your errors look more serious.  Good luck
