### ISSUE TITLE
Stabilize API for a 0.2.0 release

### ISSUE THREAD

**Issue by mattsse** [mattsse/chromiumoxide#31]
There aren't any big changes expected. 
After #17 and #16 this should be considered stable and ready for a version bump.

**Comment by gmalette** [comment]
Would you be able to release it 0.2 to crates.io please?

**Comment by mattsse** [comment]
Hi @gmalette publishing was blocked by `async-tungsenite` not being on crates with the tokio 1.0 upgrade at that time. I updated the dependency and 0.2 is live on crates.io now
