### ISSUE TITLE
async_trait is allowed or not

### ISSUE THREAD

**Issue by DCjanus** [mattsse/chromiumoxide#41]
Hi, I was trying to implement network hook like [headless_chrome::enable_request_interception](https://docs.rs/headless_chrome/0.9.0/headless_chrome/browser/tab/struct.Tab.html#method.enable_request_interception), and I hope to expose a trait `Hook`, like this:

```rust
#[async_trait]
pub trait Hook {
    async fn call(&self, request, output);
}
```

And as you can see, this would introduce [async_trait](https://docs.rs/async_trait) as dependency, and I'm not sure is this being allowed or not.

**Comment by mattsse** [comment]
Hey,
I'm generally not opposed to introducing `async_trait`, however I'm not quite sure whether it makes sense here.
If I understood your request correctly you want to implement support for [Network.setRequestInterception](https://vanilla.aslushnikov.com/?Network.setRequestInterception)? According to the docs, this is deprecated in favour of `Fetch.enable`. Puppeteer also seems to use `Fetch.enable` [here](https://github.com/puppeteer/puppeteer/blob/8695759a223bc1bd31baecb00dc28721216e4c6f/src/common/NetworkManager.ts#L203), and the [chromiumoxide command here](https://docs.rs/chromiumoxide/0.2.0/chromiumoxide/cdp/browser_protocol/fetch/struct.EnableParams.html), which enables issuing of [`Fetch.requestPaused`](https://vanilla.aslushnikov.com/?Fetch.requestPaused) events.

After having a quick look at `headless_chrome`'s method, this hook trait callback should execute on arrival of those events, correct?
There is already a way to subscribe to events, have you checked the [`EventListener`](https://docs.rs/chromiumoxide/0.2.0/chromiumoxide/page/struct.Page.html#method.event_listener) for the `Page` and a PR that would add event listener for the browser #39 

For me this hook trait would make sense if we want to add designated support for event callbacks, but I'm not sure whether this makes a huge difference compared to the existing event stream functionality.

**Comment by DCjanus** [comment]
I'm tring to implement a server-side render service via headless chrome, and I need to hook all network request from the page , to make sure all components has been loaded.
I do believe `EventListener` is a useful, and I known how to use it. But in my view, it's low level API for me, and same to others.
I would implement the high level API for my self, and maybe for others.

**Comment by DCjanus** [comment]
Without `async_trait`, there would be some boring code for peopel who want to impl `Hook` trait. Of course, that's not a so important.

(Sorry for my terrible English,)

**Comment by mattsse** [comment]
I believe I got your point and I also think this may be beneficial for others, so I for sure welcome contributions on this :)
