### ISSUE TITLE
examples "wiki-tokio" can't click correctly "input#searchInput"

### ISSUE THREAD

**Issue by thouger** [mattsse/chromiumoxide#43]
i try to run `cargo run --example wiki-tokio --features="tokio-runtime"`,it would be click `input#searchInput` and input text about "Rust programming language".But it actually click the element that is `#ca-history`,so the exmaples "wiki-tokio" finally will open `https://en.wikipedia.org/w/index.php?title=Main_Page&action=history`.I've been thinking for a long time, but I don't know why.My chrome version is `Version 89.0.4389.90 (Official Build) (64-bit)`

**Comment by thouger** [comment]
I want to further find out the reasons, would you mind telling me how to communicate with chrome?Why didn't you original choosed [webriver](https://hg.mozilla.org/mozilla-central/file/tip/testing/webdriver)?

i'm came from [voyager](https://github.com/mattsse/voyager),you ready good at Rust and i have been learning from you recently. Thank you very much for your contribution,i just new at Rust.

**Comment by mattsse** [comment]
The webdriver API is different from chrome's native [devtools protocol](https://chromedevtools.github.io/devtools-protocol/) which is unique for chromium based browsers. You can read the how it works in detail, however the gist of it is, if you run chromium with the `--remote-debugging-port=0` argument, it will expose a websocket port that listens for commands, such as [`Page.PrintTPDF`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF), executes them and returns a response. To describe these commands, chromium uses a special format, like for [browser protocol](https://github.com/mattsse/chromiumoxide/blob/main/chromiumoxide_cdp/browser_protocol.pdl), this allows us to parse them and generate all the rust types via a [build script](https://github.com/mattsse/chromiumoxide/blob/main/chromiumoxide_cdp/build.rs). The API of chromiumoxide basically just bundles a set of commands to convenient operations. 
If you want to know more, about the devtools protocol, you should look up puppeteer, the most sophisticated devtools api written in node, there should be a lot of tutorials about how it works in detail.

**Comment by thouger** [comment]
thanks mattsse!your erudition is amazing, I will go into deeper research here, if there is any new discovery, I will reopen issues,
