### ISSUE TITLE
How to implement the 'Copy' trait for `chromiumoxide::Browser`?

### ISSUE THREAD

**Issue by dwisiswant0** [mattsse/chromiumoxide#51]
The code looks like this:

```rust
async fn main() {
...
	let (browser, _handler) = Browser::launch(
		BrowserConfig::builder()
			.build()
			.unwrap()
		)
		.await
		.unwrap();
...
	for u in urls {
		check(browser, &u).await // it's supposed to run with threading
	}
...
}

async fn check(browser: Browser, url: &str) {
	let page = browser.new_page(url).await.unwrap();
	let check: bool = page.evaluate("some_script")
		.await
		.unwrap()
		.into_value()
		.unwrap();
...
}
```

I'm really new into Rust, but - this confuses me for threading/concurrent purposes.

Any workarounds for those?

**Comment by mattsse** [comment]
try wrapping the browser object in an [`Arc`](https://doc.rust-lang.org/stable/std/sync/struct.Arc.html)

But since your check function essentially depends on the `Page` object you could try something like:

```rust
futures::join_all(urls.into_iter().map(|url| async {browser.new_page(url).await.unwrap(); ...})).await;
```

**Comment by dwisiswant0** [comment]
Thanks for the quick reply, @mattsse! But it's the same, it outputs as:

```rust
future::join_all(urls.into_iter().map(|url| async move {
	let page = browser.new_page(&url).await.unwrap();
	let vuln: bool = page.evaluate("TBD")
		.await
		.unwrap()
		.into_value()
		.unwrap();
...
})).await;
```

Output: `cannot move out of 'browser', a captured variable in an 'FnMut' closure` and `move out of 'browser' occurs here`.

**Comment by mattsse** [comment]
yes, because you're borrowing the browser, you need to wrap it into an `Arc` and clone it before moving into the closure

**Comment by dwisiswant0** [comment]
> yes, because you're borrowing the browser, you need to wrap it into an `Arc` and clone it before moving into the closure:
> 
> `let browser = Arc::new(browser);`
> 
> `.map(|url| (url, Arc::clone(&browser)).map(|(url, browser)| async move {..})`

Here's results: `method cannot be called on '(std::string::String, Arc<chromiumoxide::Browser>)' due to unsatisfied trait bounds`
![Screenshot_2021-06-21_18-23-33](https://user-images.githubusercontent.com/25837540/122754532-fff79680-d2bd-11eb-954a-f1faee476f3f.png)

**Comment by dwisiswant0** [comment]
^ On that real-case, this is how I declare `coll` as vector:
```rust
let mut coll: Vec<String> = vec![String::new(); 0];
```

**Comment by mattsse** [comment]
can you post your whole code?

**Comment by dwisiswant0** [comment]
Closing this as it's resolved.
