### ISSUE TITLE
Add the option to download chromium bin on demand

### ISSUE THREAD

**Issue by mattsse** [mattsse/chromiumoxide#7]
Currenlty `chromiumoxide` relies on `chromium` being already installed on the system.
Like puppeteer an option to bundle a chromium executeable directly should be supported

**Comment by dfrankland** [comment]
Continuing the conversation from #25&hellip;

I was looking into how `headless_chrome` automatically installs `chromium` and it doesn't look like it is too much work to port it over:

"fetcher" for downloading the `chromium` binary:
https://github.com/atroche/rust-headless-chrome/blob/1f63d697d8491fc222eb118a25684e380e00ecbb/src/browser/fetcher.rs

Using the "fetcher" to download and get the path of the `chromium` binary:
https://github.com/atroche/rust-headless-chrome/blob/1f63d697d8491fc222eb118a25684e380e00ecbb/src/browser/process.rs#L147-L158

I wonder if we could make a further improvement to download both the PDL from https://github.com/ChromeDevTools/devtools-protocol and `chromium` revision that match so there's never a conflict.

**Comment by mattsse** [comment]
Yes, this should generally be straight forward to implement/adapt from `headless_chrome`.
Maybe we could include this in the `pdl` generator pipeline since the `Generator` already accepts an option to set the location of the pdl files. 
A separate cli to download everything is also probably useful.
There are some artifacts already laying around in [chromiumoxide_pdl/src/build/mod.rs](https://github.com/mattsse/chromiumoxide/blob/main/chromiumoxide_pdl/src/build/mod.rs). 

> I wonder if we could make a further improvement to download both the PDL from

This would be an improvement indeed. [chromedp/pdlgen](https://github.com/chromedp/pdlgen) does the exact same thing.

**Comment by Sytten** [comment]
Hey there! I just found this library while looking for an async alternative to `headless_chrome`. I will try to push a PR next week to implement the fetcher. Would you want that behind a feature flag or not?

**Comment by mattsse** [comment]
great, sgtm!

**Comment by Sytten** [comment]
PR is up for review @mattsse @dfrankland when you have time to take a look :)
