### ISSUE TITLE
Miss "Break on start" pause reason for paused event

### ISSUE THREAD

**Issue by PrivateRookie** [mattsse/chromiumoxide#75]
if launch node inspect process with `--inspect-brk`, the first paused event was fire with pause reason "Break on start", bug [PauseReson](https://docs.rs/chromiumoxide_cdp/0.3.1/chromiumoxide_cdp/cdp/js_protocol/debugger/enum.PausedReason.html) missing this feature variant.

my env:
- node 16.x
- chromiumoxide_cdp 0.3.1

**Comment by mattsse** [comment]
these are all generated from the chromium pdl files like 
https://github.com/mattsse/chromiumoxide/blob/main/chromiumoxide_cdp/browser_protocol.pdl
you can in fact override them.
There are definitely newer releases in the chromium source tree, happy to accept a PR with newer pdl's

**Comment by PrivateRookie** [comment]
I opened a PR #76  to add new pause variant, please review it.

**Comment by mattsse** [comment]
thanks!
lgtm, closing this now
