### ISSUE TITLE
Improve javascript function evaluation

### ISSUE THREAD

**Issue by mattsse** [mattsse/chromiumoxide#8]
The `Page::evaluate` interface expects an expression to be evaluated in the browser

`page.evaluate("1+2")` results in a value of `3` where as `page.evaluate("() => { return 1+2;}")`  results in a value of `Function`, because the `Runtime.evaluate` command expects an expression.

To evaluate (async) functions a way to determine whether the `expression` passed to `Page::evaluate` is in fact a javascript function, if so we  send this as `Runtime.callFunctionOn` instead.

This could be achieved by writing a poor parser to distinguish between expression | function, or change the type of the `expression` param that the `evaluate` functions accept to a new trait (something like `Evaluable`) and two types `Expresion` and `JsFunction` that are bundled in an enum. 

There should be a new api function: `Page::evaluate_function` that uses `Runtime.callFunctionOn`.
The most intuitive solution would probably be `Page::evaluate` strictly for `Runtime.evaluate` and `Page::evaluate_function` for `Runtime.callFunctionOn` and possibly additional checks on `Page::evaluate`

**Comment by shulcsm** [comment]
Because of this `set_content` is currently broken. It should call `evaluate_function` with content as argument
